services:
  makangoapi:
    build:
      context: review-service
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORTS=80
    restart: unless-stopped