name: Snyk Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  snyk:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Snyk
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # -----------------------------
      # SCA (Open Source)
      # -----------------------------
      - name: Run Snyk Open Source
        run: snyk test --severity-threshold=high
        working-directory: ./review-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # -----------------------------
      # SAST (Code)
      # -----------------------------
      - name: Run Snyk Code
        run: snyk code test --severity-threshold=high
        working-directory: ./review-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # -----------------------------
      # Build Docker Image
      # -----------------------------
      - name: Build Docker Image
        run: docker build -t review-service:latest .
        working-directory: ./review-service

      # -----------------------------
      # Container Scan
      # -----------------------------
      - name: Run Snyk Container
        run: snyk container test review-service:latest --file=Dockerfile
        working-directory: ./review-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
