name: Snyk Security

on:
  push:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      # -----------------------------
      # SAST (Code Scan)
      # -----------------------------
      - name: Snyk Code test
        run: snyk code test --sarif
        working-directory: review-service

      # -----------------------------
      # SCA (Open Source)
      # -----------------------------
      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects
        working-directory: review-service

      # -----------------------------
      # Build Docker Image
      # -----------------------------
      - name: Build Docker image
        run: docker build -t review-service:latest .
        working-directory: review-service

      # -----------------------------
      # Container Scan
      # -----------------------------
      - name: Snyk Container monitor
        run: snyk container monitor review-service:latest --file=Dockerfile
        working-directory: review-service

      # -----------------------------
      # Upload SARIF
      # -----------------------------
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: review-service/snyk-code.sarif
