name: Snyk Security Scan

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  snyk-security:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # ---------------------------------
      # Restore dependencies (SCA prep)
      # ---------------------------------
      - name: Restore dependencies
        working-directory: review-service
        run: dotnet restore

      # ---------------------------------
      # SCA - Open Source Scan
      # ---------------------------------
      - name: Run Snyk Open Source (SCA)
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium
          command: test
        working-directory: review-service

      # ---------------------------------
      # SAST - Code Scan
      # ---------------------------------
      - name: Run Snyk Code (SAST)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test review-service --severity-threshold=medium

      # ---------------------------------
      # Build Docker Image
      # ---------------------------------
      - name: Build Docker image
        run: |
          docker build -t review-service:latest ./review-service

      # ---------------------------------
      # Container Image Scan
      # ---------------------------------
      - name: Run Snyk Container Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: review-service:latest
          args: --file=review-service/Dockerfile --severity-threshold=medium
